### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by jemsab** [OCamlPro/ocp-cmtdeps#1]
Hi OCamlPro!

When trying to access the project documentation all the links in the documentation appear to be broken, when clicking on each link I get a `404 file not found error`

**Comment by lefessan** [comment]
Thanks! Indeed, I didn't trigger Github Pages, it should be fixed now. 
However, don't expect much documentation there, the tool is quite simple: just call it from within a `dune` project, and it generates a `deps.pdf` file, with the graph of dependencies... (and some verbose output, if the pdf is too complex).
